/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

#pragma once

#include <executorch/runtime/core/exec_aten/exec_aten.h>

#ifdef EXECUTORCH_SELECTIVE_BUILD_DTYPE
// include header generated by
// executorch/codegen/tools/gen_selected_op_variants.py
#include "selected_op_variants.h"
#else
inline constexpr bool should_include_kernel_dtype(
  const char *operator_name,
  executorch::aten::ScalarType scalar_type
) {
  return ((std::string_view(operator_name).compare("_softmax.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("add.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("addmm.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("any.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Bool))
 || ((std::string_view(operator_name).compare("bmm.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("clone.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("convolution.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("eq.Scalar_out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Bool || scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("expand_copy.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("full_like.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("gelu.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("logical_not.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Bool))
 || ((std::string_view(operator_name).compare("mm.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("mul.Scalar_out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("native_layer_norm.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("permute_copy.out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Float))
 || ((std::string_view(operator_name).compare("where.self_out") == 0)
        && (scalar_type == executorch::aten::ScalarType::Bool || scalar_type == executorch::aten::ScalarType::Float));
}
#endif

namespace torch {
namespace executor {
#define ET_INTERNAL_CHECK_SELECTIVE_BUILD(enum_type)               \
  do {                                                             \
    if (!should_include_kernel_dtype(et_switch_name, enum_type)) { \
      ET_LOG(                                                      \
          Error,                                                   \
          "dtype '%" PRId8 "' not selected for operator %s",       \
          static_cast<int8_t>(enum_type),                          \
          et_switch_name);                                         \
      torch::executor::runtime_abort();                            \
    }                                                              \
  } while (0)

} // namespace executor
} // namespace torch

#include <executorch/runtime/core/exec_aten/util/scalar_type_util.h>
